### ISSUE TITLE
clarify 'Numeric' in tables?

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#1]
In most tables, the term **"Numeric"** in 'type' column is interchangeably used for both **Integer** and **Floating Point**.

* Older tables tend to use *numeric*, whereas
* Newer tables use *integer* and *floating point*.
* No table uses _both_ numeric and integer.

What action should we take?
- should we eliminate all uses of *Numeric* in tables and replace it with *Integer* and *Floating Point*, as needed ? **[I propose this solution]** or
- should we replace all uses of *Integer* with *Numeric* ?
In literature, *Integer* and *Numeric* appear as identical.

Typical citations of numeric vs integer:
* ![numeric_and_integer](https://user-images.githubusercontent.com/33229181/54488473-ce0b5480-48aa-11e9-92b6-d37e12fd6b41.PNG)
* ![numeric_in_tables](https://user-images.githubusercontent.com/33229181/54488474-ce0b5480-48aa-11e9-88c1-39b8cf1f36a5.PNG)
* ![integer_and_floating_pont](https://user-images.githubusercontent.com/33229181/54488518-3d814400-48ab-11e9-85dd-74263d8c34da.PNG)

**Comment by economidis-nick** [comment]
@DrCaFr  we eliminated all uses of Numeric in tables and replaced them with Integer and Floating Point, as needed. Do you accept the changes ?

**Comment by DrCaFr** [comment]
Hi Nick,

yes, I agree: "Integer" is much clearer to understand for a non-native English speaker, than "Numeric". Hence, please substitute "Numeric" by "Integer" - though still checking, whether a "Floating Point" could still have been meant ;-) 

Thanks a lot,

  Carsten
