### ISSUE TITLE
revise seamweld technologies

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#10]
Fix sections where `friction` and `brazing` technologies are missing.

![image](https://user-images.githubusercontent.com/33229181/54491236-67dffb00-48c5-11e9-9f9f-3d582ea5247a.png)

**Comment by economidis-nick** [comment]
@DrCaFr , in the xsd, <flared joint> used to support only 'arc' technology.
Is brazing and friction needed to be added for this type?

<flared joint> is the only seam type which does not support all welding technologies.
Is it definite that 'resistance' and 'laser' technologies are impossible for this seam type?
or should these technologies be added as options, just in case something becomes technologically possible?

**Comment by DrCaFr** [comment]
Hi Nick,

you refer to "Flared Joint", right?
In deed, I can imagine laser very well. Resistance welding is more typical for points than for lines. Lines would require kind of a wheel as electrodes. But, who knows? May have been invented, meanwhile? 
So, yes: Please allow all technologies!

Best regards,

  Carsten
