### ISSUE TITLE
3 weld positions in Y-joint

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#13]
@DrCaFr , you mention that 3 welding positions are possible in Y-joints:
> Because there can even be a weld from the opposite side! (i.e., from “below” in figure 61). 

![image](https://user-images.githubusercontent.com/33229181/54491468-7e875180-48c7-11e9-88a9-ac93eb1a888b.png)

If there was a weld from the opposite side, then that would form a **cruciform joint**, which is already a subtype on its own.
Even if there is another sheet to connect, the possible welding positions would be 4, not 3.

Therefore, I still think the text is wrong. It must be a remnant, since the days before the K-Joint.
Would you agree?

**Comment by economidis-nick** [comment]
@DrCaFr 
I disagree with your comment on Y-joint:

![image](https://user-images.githubusercontent.com/33229181/54872284-34700580-4dca-11e9-8520-a5c3ea2bfbd4.png)

**Comment by DrCaFr** [comment]
Hi Nick,

no, I did _not_ refer to a cruciform joint!
I wanted to describe the following situation:

![grafik](https://user-images.githubusercontent.com/18173895/57101929-9bb29b00-6d22-11e9-9886-5e265015e255.png)

I re-assign the issue to you and I am looking forward to your feedback!

Best regards,

  Carsten

**Comment by DrCaFr** [comment]
Closed by mistake.

**Comment by economidis-nick** [comment]
added footnote so that future generations don't question it again

**Comment by economidis-nick** [comment]
added footnote so that future generations don't question it again
