### ISSUE TITLE
K-joint should have 3 weld positions, not 4

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#14]
I remember that K-joint had 3 welding positions. There is one weld connecting the 2 non-base sheets, not 2 we;ds, because otherwise we should have used 2 Y-Joints to describe it.

The pictures display exactly this:
![image](https://user-images.githubusercontent.com/33229181/54491746-7c25f700-48c9-11e9-8ac0-27f73e91ec70.png)

Therefore, your fix in text should be the opposite, ie:
> There are three potential welds ...   K-joint supports up to three weld positions
and **not**
> There are four potential welds ...   K-joint supports up to four weld positions

If you agree, I'll do the fix

![image](https://user-images.githubusercontent.com/33229181/54491735-66b0cd00-48c9-11e9-98ac-b92c95218657.png)

**Comment by economidis-nick** [comment]
@DrCaFr 
1. Agree on your comment about 4-sheet overlap -- added footnote:
2. Disagree with your comment on Y-joint -- my explanation in in picture below
3. Disagree with your comment on K-joint  -- my explanation in in picture below

![image](https://user-images.githubusercontent.com/33229181/54872284-34700580-4dca-11e9-8520-a5c3ea2bfbd4.png)

![image](https://user-images.githubusercontent.com/33229181/54872286-494c9900-4dca-11e9-8066-6ea3fa2e5d35.png)

![image](https://user-images.githubusercontent.com/33229181/54872289-5b2e3c00-4dca-11e9-8a06-83e7c5796ed4.png)

**Comment by DrCaFr** [comment]
Similar to issue #13: There can be a laser beam from below:

![grafik](https://user-images.githubusercontent.com/18173895/57102373-a4f03780-6d23-11e9-940d-85533031fe89.png)

Please re-consider!
