### ISSUE TITLE
cannot use fatxml.xsd to validate the <femdata> element

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#18]
cannot  use `<xs:include>` or `<xs:import>` the schema of FATXML, because `<CAE_DATA>` is not referenceable.

Only `<CAD_META_DATA>` element is exposed from the FATXML's schema.
`<CAE_DATA>` is embedded well inside the `<CAD_META_DATA>` element, 
and we cannot include the FATXML's schema in `xmcf3.xsd`.

Schema of FATXML must be modified in order to expose the CAE_DATA element or CAE_DATA type.

@DrCaFr , do you see any other way?

**Comment by DrCaFr** [comment]
Thank you, Nick, for your analysis!
I would suggest to approach Mr. Schulte-Frankenfeld with a change request to FATXML.
I am sure, he is aware of the importance of standards and the need to minimize redundancies, and will foster the process in VDA-AK 27. 
Can you please draft the required change?

**Comment by economidis-nick** [comment]
Here's the decision we took on Darmstadt May 2019 meeting
![image](https://user-images.githubusercontent.com/33229181/66666306-ff89aa00-ec58-11e9-965e-6e1506bb8d31.png)


## The FATXML schema file will break up into two files:

 *   entity.xsd  and
 *   NEW_FATXML_META_DATA.xsd

where NEW_FATXML_META_DATA.xsd will include entity.xsd.

    Use diff to compare the original and proposed FATXML schema files:
    -    entity.xsd defines a type "entity_type"
    -    NEW_FATXML_META_DATA.xsd  extends this type, to build <ENTITY>   



## On the xmcf_3_0_1.xsd side, we will only have to
*    include entity.xsd at the begining of the schema
~~~~xml
          <?xml version="1.0"?>
          <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
                     xmlns:xerces="http://xerces.apache.org" elementFormDefault="qualified" vc:minVersion="1.1">
        +      <xs:include schemaLocation="entity.xsd"/>
~~~~
*    and constrain our "femdata_type" to use "entity_type" from entity.xsd:
~~~~xml
            <xs:complexType name="femdata_type">
                <xs:sequence>
         +          <xs:element name="entity" type="entity_type" minOccurs="0" maxOccurs="unbounded"/>
         -          <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
~~~~

## Results:
Using this refactoring, FATXML  format remains completely unchanged.
xMCF will have a format for <femdata> like so:

~~~~xml
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <xmcf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="xmcf.xsd">
            <version> 3.0.0 </version>
            <connection_group id="1">
                <connected_to>
                    <part index="1" label="PART_7000700" pid="20123213"/>
                    <part index="2" label="PART_9000800" pid="90123213"/>
                </connected_to>
                <connection_list>
                    <connection_0d>
                        <femdata>
                            <NASTRAN>
                                <entity>
                                    <TYPE>CHEXA</TYPE>
                                    <ID>150</ID>
                                    <ID>151</ID>
                                </entity>
                                <entity>
                                    <TYPE>CBAR</TYPE>
                                    <ID>180</ID>
                                </entity>
                            </NASTRAN>
                        </femdata>
                        <spotweld/>
                        <loc>-1 -1 -1</loc>
                    </connection_0d>
                </connection_list>
            </connection_group>
        </xmcf>
~~~~

**Comment by DrCaFr** [comment]
Review finished. 
Please pay attention to the 2 new footnotes I added to sec. 5.2.1.1 / page 32:

7  Cite from FATXML V1.2 R2 file „02_FATXML_General_Introduction_Data_Format_V1.2_R2_170515.pdf“, p. 5: „Currently the Solver-Codes PAM-CRASH, LS-DYNA, RADIOSS, OPTISTRUCT, **MSC-** NASTRAN and PERMAS support the FATXML-Format […]. ABAQUS currently supports the FATXML-Format only with special defined comment cards […] “ 

8  Attention: FATXML example file „SILVERADO_FATXML_v1.2_20170515.fatxml“ states „&lt;NAME>**MD** NASTRAN&lt;/NAME>“. Hence, it needs to be clarified, which of both names is valid.

**Comment by economidis-nick** [comment]
Then I assume with agree with my changes  in 5.2.1.1 (femdata).
I will 'accept' them in the Word document

**Comment by economidis-nick** [comment]
Waiting for AK27 to provide the definition for <entity>, so the Fatxml schema can be included in the xMCF schema.

**Comment by economidis-nick** [comment]
@DrCaFr , should we add a copy of the FATXML*.xsd schemas?
Or should we wait until they are officially published ? We should then update the URL in the schemaLocation...

**Comment by DrCaFr** [comment]
I’d prefer a _reference_ to the FATXML location. It makes it much clearer, who owns this piece of XML schema, than _copying_ would do.  
&mdash; Provided, this referencing is technically feasible.

**Comment by economidis-nick** [comment]
### FATXML entity schema
on 26th May 2020, the FATXML ENTITY 1.2 R3 schema was uploaded to the VDA server.
We updated all the links in the xMCF document.

### Resolution
On 27 May 2020 we agreed that we should keep a copy of FATXML_ENTITY schema along with the xMCF schema.

Neither the xMCF schema nor FATXML schema gets a permanent URL, partly because VDA server is not meant to provide a persistent URL.
Other arguments supporting this is that for some OEMs access to such a URL would be impossible.
Therefore, the schemas will be provided in a zip folder and stored in the VDA server, along with the examples and documentation.

**Comment by DrCaFr** [comment]
Maybe worth to be mentioned:  
ISO provides _stable_ URIs for so-called "electronic inserts".
For example, STEP AP 242 XML resides at  
http://standards.iso.org/iso/ts/10303/-3001/-ed-1/tech/xml-schema/bo_model.
