### ISSUE TITLE
Version code "3.0" vs. "3.0.0"

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#21]
Sec. 5.2 says: "The version code of xMCF files following this document is 3.0." 
However, the examples use "3.0.0". - Needs to be fixed!

**Comment by economidis-nick** [comment]
You're probably referring to section 5.1.2.

I changed it to read:
> The version code of xMCF files following this document is **3.0.0**

which is more accurate
