### ISSUE TITLE
More detailed explanation of attributes “label” and “pid” - for the non-FEM-natives

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#23]
June 2018 meeting provided following feedback from Production Planning application:
> Standard document needs some more explanation / additional recommendation,  
e. g. difference between <part/> attributes “label” and “pid”.

**Comment by economidis-nick** [comment]
@DrCaFr , isn't there enough information in sections 4.1.1 and 4.2 ?!?

**Comment by DrCaFr** [comment]
Well, actually it was not clear enough to prevent the Production Planning application to use "Part Label" for the _name_ of a part (Bauteilbezeichnung) and "PID" for its part code (Sachnummer). 
Unfortunately, on both parties (BMW & PROSTEP) staff changed meanwhile. Hence, we cannot ask for an explanation, anymore.

**Comment by DrCaFr** [comment]
I suggest to ask the next AK meeting about whether anyone faced similar issues. 
If not, we should reject the issue.
