### ISSUE TITLE
Part instance identifier ("instance")

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#24]
June 2018 meeting provided following feedback from Production Planning application:
> Part instance identifier for ditto parts (in addition to part _label_/part code), e.g.:  
`<part index="1" label="rim_16" instance="5"/>`
---
I suggest discussing this with VDA AK.

**Comment by economidis-nick** [comment]
We left it for discussion for a following release.
It should not be a blocker for xmcf v3.1

**Comment by DrCaFr** [comment]
Discussion during 2021-10-21 meeting:  
- Attribute `instance` is optional.  
  (To be described: What happens, if it is missing. Probably, behave as nowadays.) 
- Attribute `instance` is of alphanumeric type. (Following e.g. STEP standard.)

**Comment by DrCaFr** [comment]
@economidis-nick: Review completed with commit b42b379201563b8040ec1ebc9a3566489e3a2908. 

@mweinert611: Which further steps do we need for acceptance?

**Comment by mweinert611** [comment]
Normal process is the apporval in the full working group. 
Just an idea we can discuss tomorrow. 
I would also not have an issue with sharing the proposal via email with the full team and ask for approval or better for rejections/concerns if any.
Can be discussed tomorrow.

**Comment by DrCaFr** [comment]
Was closed by mistake.

**Comment by mweinert611** [comment]
implemented in doc and agreed by full working group
