### ISSUE TITLE
"hardness" attributes in <rivet>

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#3]
**`hardness`** in needs to be incorporated in **all `<rivet>` types**.
Not just in `<self_piercing_rivet>`

@DrCaFr , I will do it, but I may need you contribution in text.

ref:
![rivet_hardness](https://user-images.githubusercontent.com/33229181/54488933-fa759f80-48af-11e9-80f8-2c4613d8d8ae.PNG)

**Comment by economidis-nick** [comment]
@DrCaFr , please review the change in the document, so @mkalaitz can update the schema accordingly

**Comment by DrCaFr** [comment]
Hi Nick, hi Maria,

in principle, I am fine with the change. 
However, we always said, χMCF 3.0.1 would not change the syntax, compared to χMCF 3.0.0. 
In this case, χMCF 3.0.0 files would become invalid, if they contain a self piercing rivet with a hardness attribute. 
So, can we consider to allow the hardness at the old positions, too, in χMCF schema, but add an according comment/hint, similar to e.g. Doxygen's "[\deprecated](http://www.doxygen.nl/manual/commands.html#cmddeprecated)"?

Thanks and best regards,

  Carsten

**Comment by economidis-nick** [comment]
@mkalaitz , please modify the xsd so that `hardness` is allowed under `<self_piercing>` rivet **only** under version "3.0.0".

**Comment by economidis-nick** [comment]
@mkalaitz, please make sure that   both of these work
`<version>  3.0.0  </version>`
`<version>3.0.0</version>`

Doesn't this assertion need a 'contains' expression?
`( version/text() = '3.0.0')`

**Comment by DrCaFr** [comment]
Above communication sounds plausible to me. 
I still need to review the schema as a whole, though. 
Hence I close this issue.
