### ISSUE TITLE
Update directory and file name, please.

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#30]
Hi @economidis-nick ,
approaching the AK meeting - shouldn't we rename directory "V3.1" to "V3.0r1" and file name "Documentation_xMCF_File_v3.0_2019-03-23.docx" to "Documentation_xMCF_File_v3.0r1.docx"?
Best regards,
  Carsten

**Comment by economidis-nick** [comment]
Acknowledged

**Comment by DrCaFr** [comment]
Yes, indeed: If file format version code changes, so should schema file name do. 
@economidis-nick: I agree with your suggestion.

**Comment by economidis-nick** [comment]
done

**Comment by DrCaFr** [comment]
Confirmed - thanks for all the work, changing all the instances of version codes in all the files!
