### ISSUE TITLE
self connections, stacking of parts and number of layers

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#36]
It has been observed that the definition of <connection_group> has been misinterpreted.

pages 12 & 13 of [the Darmstadt May 2019 meeting minutes](https://github.com/economidis-nick/createXSDforxMCF/tree/master/VDA_FAT_AK_25/Meetings/2019-05-28_Darmstadt) describe what changes have to be done **in a later document**, in order to fix this.

The intention of the document was to accommodate all three cases, A, B, C, with the same <connection_group> definition:
~~~~
<connected_to>
    <part index="1" label="green"/>
    <part index="2" label="red"/>
</connected_to>
~~~~
![image](https://user-images.githubusercontent.com/33229181/66425409-42a90a80-ea18-11e9-8c66-2254350a2543.png)

**Comment by DrCaFr** [comment]
Question @economidis-nick: Is there any correlation assumed between the numbering of the &lt;level/>s and the direction of the screw / laser beam?  
I guess: No.  
Hence, I suggest to mention this as a remark somewhere.

**Comment by DrCaFr** [comment]
Section "5.3.1.3 Special Topological situations" reviewed.
Minor modifications applied.
Please merge commit 90502b935343e1f595c4d0a1a8cf7b1452450a75 from "review_CF" into master branch!

**Comment by economidis-nick** [comment]
Done! 
I assume that this implies you agree with my changes on the 5.3.1.3, and I shall Accept them in the Word document.
