### ISSUE TITLE
<assy/> as contact partner

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#37]
Section "5.3.2.3	Element &lt;partner/>" starts with:
<blockquote>
Each joint partner involved in a contact is specified by the element &lt;partner/>. It is referred to by an attribute label or pid. Only those labels or pids are allowed, which are listed in <connected_to>. 
</blockquote>
However, an &lt;assy/> element as described in section "5.3.1.2	Element &lt;assy/>" does not have _neither_ label _nor_ pid. 

Question: Does this imply that &lt;assy/> elements cannot be used in contact definitions?  Or do we need to provide an identifier for assemblies, too?

**Comment by DrCaFr** [comment]
Ok, the example in section 5.3.2.4 suggests that a contact definition "reaches through" an &lt;assy/> down to the contained &lt;part/>.  
This is understandable in case the parts in an assembly have different material and hence different friction coefficients.  
But is this really intended this way?

**Comment by economidis-nick** [comment]
@DrCaFr , I don't think any of these were intentional.
I remember that, initially, you and I have proposed for `<partner>` to refer to the corresponding `<part>` using the `part`'s `index`.
Dr. Zhang preferred that we use the label instead, because it would make the xml more human-readable. And that's how we came about this issue.
But since you have found this inconsistency, I propose that we change this definition back to the original proposal and use the `part`'s `index`.
What would you agree?

**Comment by DrCaFr** [comment]
This is not a beautiful, but a pragmatical solution. 
I agree.

**Comment by economidis-nick** [comment]
@DrCaFr , in table 14 of 5.3.2.1 I came across to the following *Constraint*:
> Any set (= non-ordered pair) of physical contact   partners must not appear more than once within a <contact_list/>.

Does that mean that we cannot define a contact in self-connecting joints?
If so, then I think we should remove this constraint.

**Comment by economidis-nick** [comment]
@DrCaFr , please review this change.
If you agree, I will go on and modify the schema and examples, as well

**Comment by DrCaFr** [comment]
See my commit cbb64d84363ef288827bb0fa07447f613cac5507.

**Comment by economidis-nick** [comment]
<contact><partner> was left as an element, instead of an attribute in <contact>.
This may have the opportunity to get an attribute, under <partner> in the future.

**Comment by DrCaFr** [comment]
> was left as an element, instead of an attribute in .
> This may have the opportunity to get an attribute, under in the future.

For convenience' sake: This was Nick's answer to my question
> What is the benefit of having two <partner/> elements with one attribute each, compared with only one element, having two mandatory attributes (say, part_index_1 and part_index_2)? 
(The latter version would offer a shorter notation.)

I accept Nick's answer: ✔️
