### ISSUE TITLE
Do we need attribute "sheet_angle" for I-Weld?

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#39]
Section '8.2.8.5	Element "sheet_parameter"' lists "sheet_angle" as parameter for I-Weld in both, Table 99 and Example A.   
Is this rally meaningful?

**Comment by economidis-nick** [comment]
On 27 May 2020 we agreed that I-Welds have no use for 'sheet-angle' attribute.
So, I removed it from the document and schema, altogether.
