### ISSUE TITLE
"1 & optional" convention to be expressed in text

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#4]
The convention  **Multiplicity = 1** and **optional** instead of
**Multiplicity = 0-1** and **required** should be written in a text location, 
not inside a comment.

@economidis-nick  to implement this

![consistent_optional](https://user-images.githubusercontent.com/33229181/54489051-fa29d400-48b0-11e9-8c1e-5655b3e78a8d.PNG)

**Comment by economidis-nick** [comment]
Provided a description used for the multiplicity.

![image](https://user-images.githubusercontent.com/33229181/54871161-d1c23e00-4db8-11e9-83d4-2167868be607.png)

@DrCaFr , please confirm

**Comment by DrCaFr** [comment]
Hi Nick,

according to [w3.org](https://www.w3.org/TR/xmlschema-0/#attribute-use), there _is_ an XML Schema Attribute "use", but _no_ "status". 
Please consider search-and-replacing all the other table headings - or decouple XML and χMCF wording by a modified description on p. 25!

Thanks a lot,

  Carsten

**Comment by economidis-nick** [comment]
Done. please  review

**Comment by DrCaFr** [comment]
Changes confirmed. I close this issue.
