### ISSUE TITLE
Part _pname_ identifier

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#41]
In 9th Dec 2019 meeting in Cologne, Magna has reported that they cannot use xMCF with Abaqus, because Properties in Abaqus are identified by a Name, not a PID.

We noted that we would consider adding an attribute in `<part>`, like `plabel` or `pname` for this purpose

**Comment by economidis-nick** [comment]
This request has been handled by this commit:
feff530a48ccd1843393f9d32723f1c1c530ed66

`pname` was chosen so that it does not get mistaken with the part's label.
* either `pname` or `pid` may be used to identify a property -- but ***not both***

**Comment by DrCaFr** [comment]
See my commit 4c80f87f0e96262eb6dc34073096fd011f9a03b9, i. e. my comment to table 9.

**Comment by economidis-nick** [comment]
in accordance to your comment to table 9:
* it is now possible to have both **pid** and **pname** attribute, so that the same xml file may be used both for abaqus- and other- files. Depending on who reads it, he should choose the appropriate identifier.
