### ISSUE TITLE
clarify <connection_group>

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#42]
In 11th Dec 2019 meeting in Cologne, Mr. Catalin Runcianu of Siemens has requested that we improve the text & pictures in 2.4 (description of topology) because the wording confused on how connections should be grouped.

**Comment by DrCaFr** [comment]
Reviewed - see commit 8983f3179294058a4bd925c1f1be9cb13fef8029.

**Comment by economidis-nick** [comment]
followed your wording, and added footnote (9), on chapter 5.3 to remind reader that an empty <connected_to> element is acceptable only for the preprocessor, not for the solver
