### ISSUE TITLE
Publishing meeting results

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#45]
I raise a question:  
Shall we continue to publish the presentations of 2019-12-11, 2020-05-27 and following meetings?
(Like under https://github.com/economidis-nick/createXSDforxMCF/tree/review_CF/VDA_FAT_AK_25/Meetings.)

**Comment by economidis-nick** [comment]
On 27 May 2020 we agreed that we would continue to publish them in this repository
