### ISSUE TITLE
Contact List - Duplication?

### ISSUE THREAD

**Issue by mweinert611** [economidis-nick/createXSDforxMCF#47]
I noticed that the <contact_list/> is being used on 2 levels. Right under the <connection_group/> and also one level below under <connection_0d/> or <connection_1d/>. 
Is this a bug we need to fix in the next round (ambiguity risk) or is there any intention behind?

**Comment by DrCaFr** [comment]
Hello @mweinert611 ,  
thank you for the observation!

Indeed, section 5.3.2.5 states: 
> If necessary, local contact properties can be given within any element <connection_0d/>,  <connection_1d/> or <connection_2d/>, respectively (see section 5.3.3 Joints). In case of conflict, a local <contact_list/> overrules the global one.

Hence, this is an intended feature to keep the syntax minimal but allow for exceptions, though.

Best regards!
