### ISSUE TITLE
Screw allowed to have _more than one_ <flow_drilled> child?

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#49]
Just came across this XSD code:  
![grafik](https://user-images.githubusercontent.com/18173895/100129124-6a0fa080-2e81-11eb-9bee-26594080cb86.png)

Does this allow a screw to have _more than one_ `<flow_drilled>` child?
I don't think, this would be good &hellip;

(Refers to `xmcf_3_1_0.xsd`.)

**Comment by economidis-nick** [comment]
fixed in commit 171707d

**Comment by DrCaFr** [comment]
I confirm, issue was fixed with commit 145494419a52c044670e4a97f6d846ee54c5263c.
