### ISSUE TITLE
can </connected_to> be empty ?

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#5]
@economidis-nick proposed the change that `<connected_to>`  should be allowed to be empty.
@DrCaFr reminded an early argument that undefined connection list can lead to wrong modeling.

###  **Question:** Is the format meant to express _any phase_ of the process, or just the _final phase_, where all necessary connection information is there?

* A **complete** connection file should, indeed, have a non-empty`<connected_to>`.
* Having no connected parts, at some point, **is** a state of the connection information. 
In my opinion, this state could still be stored or transferred from one program to another.  
It is therefore a **valid format**. An invalid xmcf format is one that simply does not have `<part>` or `<assy>` as connected parts.

Not knowing the type of `<seamweld>` or `<rivet>` is not complete modelling, but it expresses an early phase of the model.

My opinion is that we should have another version of the schema, which tests for completeness.

## Reference:
![connected_to_is_optional](https://user-images.githubusercontent.com/33229181/54489889-c8693b00-48b9-11e9-8b79-ed38f43608db.PNG)

**Comment by DrCaFr** [comment]
We all know, that "Is the format meant to express **any phase** of the process" is just a _rhetorical_ question, yes? ;-)

**Comment by DrCaFr** [comment]
Standard document still contains following remark, just before section "5.3.1	Connected Objects":
<blockquote>
Remarks:  

•	An empty or missing <connected_to> (meaning a connection according only to geometric neighborhood) is not allowed by the standard. However, systems may import such files with warnings. 
</blockquote>
This remark needs to be removed.

**Comment by economidis-nick** [comment]
done
