### ISSUE TITLE
`<femdata/>` _is_ allowed on root level

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#56]
&chi;MCF 3.1 document states in section 5.2.1.1:
> The optional `<femdata/>` can be placed within any single connector^6 (relevant tags are `<connection_0d/>`, `<connection_1d/>` and `<connection_2d/>`).

where footnote 6 reads:
> Future χMCF versions may include `<femdata/>` at root level or `<connection_group/>` elements, but this is not allowed in V 3.0.

However, XML schema `xmcf_3_1_0.xsd` states that `<femdata/>` _is_ allowed on root level (lines 6-15):
```
	<xs:element name="xmcf">
		<xs:complexType>
			<xs:all>
				<xs:element ref="units" minOccurs="0" maxOccurs="1"/>
				<xs:element name="date" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="version" type="nonEmptyString" minOccurs="1" maxOccurs="1"/>
				<xs:element name="appdata" type="appdata_type" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="femdata" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="connection_group" minOccurs="0" maxOccurs="unbounded"/>
			</xs:all>
```

Hence, footnote 6 shall be modified to e.g.:
> χMCF versions 3.1 or later allow to contain `<femdata/>` at root level, but this is not allowed in V 3.0 and below. `<femdata/>` is _not_ allowed on `<connection_group/>` level in both cases.

**Comment by economidis-nick** [comment]
I agree -- I will change it shortly.

**Comment by DrCaFr** [comment]
@economidis-nick: 
Decision 2021-05-04: To be fixed before next working group meeting, which is May 20th.
