### ISSUE TITLE
Build Cross-References between STEP (ISO 10303) and χMCF

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#63]
In order to facilitate ISO standardization of &chi;MCF, a cross reference (table) between STEP and &chi;MCF shall be established.  
Cited from minutes of 2021-05-20 working group meeting:
> 1.	The &chi;MCF standard and the related conversion request was again presented to the ISO TC184/SC4 on May 10, 2021. It has been proposed to convert &chi;MCF into a PAS (Publicly Available Standard) as a first step. This allows to avoid or minimize the re-formatting of the standard. The life cycle of such a PAS is 3 years with the option to extend it another 3 years. After the 6 years in total the standard would need to be converted into an International Standard (IS).
> 2.	The audience pointed out that alignment and compliance to the STEP standard is crucial. During the PAS period, &chi;MCF would be used in a federated way. **It is required to incorporate references into &chi;MCF to cross-reference related items and terms in STEP and &chi;MCF.** In addition, standard clauses have to be added to &chi;MCF in order to meet ISO Quality System Standards.
> 3.	The timeline for creating and publishing the PAS has been proposed to May 31, 2022.

Hence, this issue addresses implementation of the bold marked part of item 2., above.

**Comment by DrCaFr** [comment]
Max to be involved in the work.

**Comment by DrCaFr** [comment]
For our technical discussion today, following slides from 2020-12-10 presentation may be useful:  

![ISO_TC_184_SC_4_PPC_LOTAR_WebCo_20201201_xMCF__V1 0 1__s17](https://user-images.githubusercontent.com/18173895/125749989-b9da4aa3-d7e0-402b-bddb-ccaf77fe03ba.png) 

![ISO_TC_184_SC_4_PPC_LOTAR_WebCo_20201201_xMCF__V1 0 1__s18](https://user-images.githubusercontent.com/18173895/125750431-33e4a8d9-ba9f-42a7-bcda-64cd4630b8b6.png)

![ISO_TC_184_SC_4_PPC_LOTAR_WebCo_20201201_xMCF__V1 0 1__s19](https://user-images.githubusercontent.com/18173895/125750456-589acd1b-d280-4611-8240-2d57f62b4299.png)

![ISO_TC_184_SC_4_PPC_LOTAR_WebCo_20201201_xMCF__V1 0 1__s20](https://user-images.githubusercontent.com/18173895/125750469-2ec999b6-1bc3-45ed-a4a5-e48b2dbe6fbd.png)

**Comment by DrCaFr** [comment]
> references into χMCF to cross-reference related items and terms in STEP and χMCF

means:
We need to have kind of a guideline how to use STEP and &chi;MCF in cooperation. It must contain 
- a correspondence table between both standards, 
- a recommendation how to use _existing_ STEP mechanisms (e.g. external references) to establish 
  - reference,
  - &hellip;  

Up to day, we do not know another example of such a task. 
Hence, we need to invent our own means.

**Comment by DrCaFr** [comment]
We should start with an example: 
- two parts, connected with a bolt and a nut. 
- "mating information", however, would probably need to be "hand crafted".

**Comment by DrCaFr** [comment]
From a previous PROSTEP project:  
![grafik](https://user-images.githubusercontent.com/18173895/125788980-7a24f9b1-22a7-402f-96cb-7881ceb0c15f.png)

**Comment by DrCaFr** [comment]
We need to discuss, whether a "MatingDefinition" relates to 
- a complete connection group  
  or else
- a single connection.

Our final recommendation should be based upon rationales.

**Comment by DrCaFr** [comment]
Max & Carsten to check, what else can be shared from our "portfolio", e. g. hand crafted AP 242 example code.

**Comment by DrCaFr** [comment]
Next meetings:
- 5th Aug.   14-15   (w/o Nick)
- 26th Aug.  14-15  (w/o Carsten)

**Comment by DrCaFr** [comment]
&hellip; assigned to @mweinert611, since I'll be on vacation :wink:

**Comment by DrCaFr** [comment]
Following diagrams derived from &chi;MCF `XSD` may be helpful for building the cross references:  
- [Overview, highest `XSD` level](https://raw.githubusercontent.com/economidis-nick/createXSDforxMCF/bb0618a50a5655ae2102079e3728dfb2d0e74680/VDA_FAT_AK_25/Material/xmcf_3_1_0__xmcf.svg)
- [0d connection](https://raw.githubusercontent.com/economidis-nick/createXSDforxMCF/bb0618a50a5655ae2102079e3728dfb2d0e74680/VDA_FAT_AK_25/Material/xmcf_3_1_0__connection_0d.svg)
- [1d connection, seam weld focus](https://raw.githubusercontent.com/economidis-nick/createXSDforxMCF/bb0618a50a5655ae2102079e3728dfb2d0e74680/VDA_FAT_AK_25/Material/xmcf_3_1_0__connection_1d__seamweld%2B.svg)
- [1d connection, hemming focus](https://raw.githubusercontent.com/economidis-nick/createXSDforxMCF/bb0618a50a5655ae2102079e3728dfb2d0e74680/VDA_FAT_AK_25/Material/xmcf_3_1_0__connection_1d%2B.svg)
- [2d connection](https://raw.githubusercontent.com/economidis-nick/createXSDforxMCF/bb0618a50a5655ae2102079e3728dfb2d0e74680/VDA_FAT_AK_25/Material/xmcf_3_1_0__connection_2d%2B.svg)

**Comment by DrCaFr** [comment]
Suggestion for the __layout of a mapping table__:

"Origin of mapping" is &chi;MCF. Due to its smaller scope, there are chances to derive an _injective_ mapping.  

| &chi;MCF             | STEP                       | Rationale |
| ------------------ | ------------------- | ---------- |
| connection_group | MatingDefinition   |                 |
| - connected_to     | &hellip;     | &hellip;     |
| - connection_list   | &empty;     | No corresponding entity in STEP. <br/> Connections carry flange partners individually. (t.b.verified!)    |
| - connection_[012]d | MatedPartRelationship     | &hellip;     |
| - - connection_[012]d_type   | &empty;     | No corresponding entity in STEP. <br/> (t.b.verified!)  |
| &hellip;     | &hellip;     | &hellip;     |
| &empty;     | MatedPartAssociation | Required by STEP syntax. |
| &hellip;     | &hellip;     | &hellip;     |
| units     | &hellip;     | &hellip;     |
| date     | &hellip;     | &hellip;     |

**Comment by DrCaFr** [comment]
> Max & Carsten to check, what else can be shared from our "portfolio", e. g. hand crafted AP 242 example code.

Material uploaded to directory [VDA_FAT_AK_25/Material/White-Paper-Extracts](https://github.com/economidis-nick/createXSDforxMCF/tree/v3_1_1_editorial_changes/VDA_FAT_AK_25/Material/White-Paper-Extracts), cf. commit 6cc3a82.

**Comment by DrCaFr** [comment]
With the "Cross-References", we have seen good progress. 

I suggest having (an)other issue(s) for
- checking broken hyper refs / URLs,
- fixing copy right information for figures we _can_ keep and removing / replacing figures we _cannot_ keep.

**Comment by DrCaFr** [comment]
@economidis-nick will update file names of example files according to new section numbering (offset of "2" to section numbers, compared to VDA-version).

**Comment by DrCaFr** [comment]
To be considered: Updating reference to XML schema and version code 
- in example files and 
- in respective examples, embedded in Word file.

**Comment by DrCaFr** [comment]
@TimGuirguis will supply an update for examples A & B on page 12 - showing how to use a HyperMesh-specific schema for a HyperMesh-<appdata/>.

**Comment by DrCaFr** [comment]
Milestone 2021-11-08 _not_ met. Hence postponed to 2022-05-01 milestone.

**Comment by mweinert611** [comment]
All changes to the document completed; ready for submission to the full working group
