### ISSUE TITLE
Enable <tangential_direction/> for more connection types.

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#64]
Cited from minutes of 2021-05-20 working group meeting:
> -	So far, the attribute tangential direction <tangential_direction/> has been defined along with <normal_direction/> for 0D connection elements but only used for robscans. It was observed that rivets can also be non-axisymmetric and hence it was requested to enable both attributes for all 0D connection types.
> -	It was agreed by the working group.

**Comment by DrCaFr** [comment]
@economidis-nick: Please add more detail, e.g. examples for rivet types etc.! 
Are there arguments for assigning it to V3.1.1?

**Comment by economidis-nick** [comment]
Allowed <tangentiaL_direction> (and <normal_direction>) for every <spotweld_0d> type.
However, it is conceivable only for <rivet> and <clinch>, apart from <robscan>, <nail> and <clip> where it already existed.
Consider 'rejecting' the changes from some subtypes if group does not agree with the change.

**Comment by DrCaFr** [comment]
@economidis-nick : At `<spotweld/>`, I found the explanation "If a sense of direction or orientation is required for the spotwelding technique, they can optionally be provided using the <normal_direction> and <tangential_direction> elements.", whereas something similar is missing at the other occasions. There, `tangential_direction` has been added to the lists of nested elements, only. 

Is this intentional?

**Comment by economidis-nick** [comment]
@DrCaFr , yes.
I added this text as an attempt to justify the existence of the 'directions' table under `spotweld`.
But I was not proud of the text so I did not paste it everywhere. 
**If** we agree to introduce directions in every `connection_0d` and we agree to a decent wording, we can paste it where appropriate.
Otherwise, if we decide to add `directions` only to **_some_** specific subtypes, a better text could be provided.

**Comment by DrCaFr** [comment]
__Decision:__  
- For reasons of compatibility, `<tangential_direction/>` stays inside the subtypes, i.e. the elements will not be raised to connection0d-level. 
- A table like "Table 37: Nested elements of element `<spotweld/>`" shall be added to any section of 0d connector subtypes, individually.
- @economidis-nick will update his suggested formulations until next meeting.

**Comment by DrCaFr** [comment]
Change was accepted by VDA AK 25 meeting on 2021-10-21.
