### ISSUE TITLE
Attribute "section" for Seam Welds (Chapter 10.2) is limited to certain selected section types

### ISSUE THREAD

**Issue by StephanHaasECS** [economidis-nick/createXSDforxMCF#68]
In the Seam Weld Chapter 8.2. there is a limited list of allowed types for the "section" attribute:

![image](https://user-images.githubusercontent.com/76047314/131841661-6403b43a-2990-466d-a456-248292237611.png)

In addition every seam type reduces this general list further. A corner joint for example only allows:

![image](https://user-images.githubusercontent.com/76047314/131842001-aab499b5-aeac-4090-95f8-908d0a43665e.png)

With this hardcoded limitation it is not possible to define for example a HY or Y section for the corner joint.

Therefore I would suggest to rethink the allowed section types for each seam type.
In addition I came accross the "HU" aka. "J" section type, which is not supported at all at the moment.

**Comment by DrCaFr** [comment]
Cited section number adapted from 8.2 to 10.2 due to inserted sections, caused by ISO-conformant reformatting.
