### ISSUE TITLE
`<loc/>` on `<connection_0d/>`level, only.

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#69]
Investigate both, &chi;MCF specification and examples, and possibly correct:  
`<loc/>` shall be beneath `<connection_0d>` only, but _not_ (again) beneath `<spotweld/>`, `<robscan/>`, and `<rivet/>`.  
Cf. tables 
- Table 35: Nested elements of `<connection_0d/>` for `<spotweld/>`
- Table 38: Nested elements of `<connection_0d/>` for `<robscan/>`
- Table 41: Nested elements of `<connection_0d/>` for `<rivet/>`

**Comment by economidis-nick** [comment]
There is no error in tables 35, 38, 41.
The tables merely state what are the nested elements of `<connection_0d>`  when connection_0d describes a spotweld.
There is no table that states <loc> is inside a <spotweld>, <robscan>, or <rivet> element.

I checked the .xsd -- it is also correct.
The examples (and tests) are all verified via the xsd.

Please explain if I missed something.

**Comment by DrCaFr** [comment]
I confirm @economidis-nick's statement.  
We just did not invest time for this investigation during our previous meeting :wink:  
Issue closed.
