### ISSUE TITLE
Fix copyright issues with figures in Word file

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#71]
For all figures contained in Word file,
- source & copy right information shall be documented. 
- The "source code" of the figure (e.g. PPT file) shall be stored in Git repository (e.g. to allow for later improvement). 
- If there are any doubts whether the figure can be used in an ISO standard, the figure must be replaced by an unproblematic one or, as final resort, deleted.

This is relevant for ISO publication.

**Comment by DrCaFr** [comment]
Commit 336396fdb5dab099f040b91ed45edd234fca9c99 contributes to this issue.

**Comment by DrCaFr** [comment]
I suggest closing this issue, since it was addressed by commit bedbda1b6d5e9bd886029b787fbf7c4321471e74 and its predecessors.

**Comment by mweinert611** [comment]
all items corrected
