### ISSUE TITLE
update example files

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#72]
* Example files are titled according to chapters. Chapters have shifted in the PAS document.
* noNamespacesShemaLocation in the example files need to be updated when the xsd permanently resides in the ISO repository

**Comment by economidis-nick** [comment]
* 1d6d694e79d14880c453f023f8a4ac6b301b6795: updated the titles of the example files (done)
* set the `noNamespacesShemaLocation` in the example files (TODO)

**Comment by mweinert611** [comment]
Item resolved as agreed with the group
