### ISSUE TITLE
Update Examples for using `<appdata/>` with own XML Name Space

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#73]
The standards spec (Word file) contains several examples where `<appdata/>` is used with an own XML name space: 
```
    <appdata>
        <MEDINA xmlns="http://servicenet.t-systems.com/medina/xMCF">
    ...
```
Since all examples addressing name spaces need to be updated to &chi;MCF version 3.1.1 and it is assumed that MEDINA will not follow this evolution, new examples are needed. 

Follows the list of examples and example files:
- Section 7.2.1	User Specific Data `<appdata/>`:
  - Example A (`<appdata/>` for MEDINA at _root_ level)         &mdash; ch5_2_1_1_exampleA.xml
  - Example B (<appdata/> for MEDINA at _connection_ level)  &mdash; ch5_2_1_exampleB.xml
- Section 7.4	A Minimalistic Example of a &chi;MCF file:
  There is only one examle in this section. &mdash; ch5_4_example.xml _and_ ch5_4_minimalistic_example.xml

**Comment by DrCaFr** [comment]
@TimGuirguis provided an example of `<appdata/>` usage by Hyperworks &mdash; however _without_ an own XML name space:  
[20211105_1236_xMCF - APPDATA Block Example.zip](https://github.com/economidis-nick/createXSDforxMCF/files/7522415/20211105_1236_xMCF.-.APPDATA.Block.Example.zip)

**Comment by DrCaFr** [comment]
The MEDINA examples mentioned above comply to attached XML schema [mcf_MEDINA.zip](https://github.com/economidis-nick/createXSDforxMCF/files/7522482/mcf_MEDINA.zip).

**Comment by TimGuirguis** [comment]
@DrCaFr would you expect a namespace/header per instance of the specific app data within the xMCF?

**Comment by DrCaFr** [comment]
> @DrCaFr would you expect a namespace/header per instance of the specific app data within the xMCF?

Hi @TimGuirguis, 
the intention of the examples mentioned above actually is to demonstrate, how a _tool specific_ XML schema can be used for the tool specific `<appdata/>` element. &mdash; This by means of a tools specific name space. 

Thus, the example you provided cannot replace the existing example. It could serve as an additional example for use of `<appdata/>` _without_ an additional schema, though.

By the way: I noticed that your example contains `<HYPERMESH/>` in "all-caps". The Word file uses "camel-caps" `<HyperMesh/>`. We could & should adjust sect. 7.2.1 & table 3 accordingly, if you agree.

Best regards

**Comment by TimGuirguis** [comment]
Hi @DrCaFr,

I'm happy for the definition to change from "camel-case" to "all-caps" for those sections. 

My understanding on what a namespace per Connection Group means for the current Medina example, is that each <appdata/> block is independent from the next block. Is this correct? 

In the example I have provided, Hypermesh is treating every <appdata/> block as the same xml. This is because we have common data shared within an <appdata/> block in the file but outside of the Connection Group definition.

**Comment by DrCaFr** [comment]
> I'm happy for the definition to change from "camel-case" to "all-caps" for those sections.

Implemented with commit a74a9f5.

**Comment by DrCaFr** [comment]
> My understanding on what a namespace per Connection Group means for the current Medina example, is that each block is independent from the next block. Is this correct?

Syntactically yes. 
Semantically not completely: Properties for connections would be defined on global level (see "Example A (`<appdata/>` for MEDINA at root level)" on page 12), which then could be referenced by several connections via `<appdata/>` on connection level (see "Example B", same page). 
For other use cases, `<appdata/>` may also/additionally reside on connection group level.  
This is explained in first paragraph od sec. 7.2.1. 


> In the example I have provided, Hypermesh is treating every block as the same xml. This is because we have common data shared within an block in the file but outside of the Connection Group definition.

I understand. MEDINA solved this by using the same schema, hence the same name space, but with different elements on 1st level below `<MEDINA/>` element: `<data_at_root/>` and `<data_at_connector/>`.  
Another option would be of course to use different / several schemas / name spaces.

**Comment by mweinert611** [comment]
Team decided not to change the example. Text changes were incorporated.
