### ISSUE TITLE
Submit final version to ISO

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#75]
Due date according to 2023-01-25 review.

Submission shall consist of:
1. Word file `ISO-CD_PAS_8329.docx` plus PDF thereof 
2. ZIP containing
   - PowerPoint file `ISO-CD_PAS_8329_Figures-master.pptx` with figures
   - SVG figures 

- [x] To be clarified: How to submit XML example files, currently collected in https://github.com/economidis-nick/createXSDforxMCF/tree/v3_1_1_editorial_changes/V3.1.1/examples?

**Comment by maxungerer** [comment]
What do you mean with "submit XML example files"? The snippets in the Word document or complete x.xml files to be uploaded to https://standards.iso.org/iso/pas/8329/ed-1/en/ ?
This remembers me that we should also provide all electronic inserts (XSD file, ...) which should go to https://standards.iso.org/iso/pas/8329/ed-1/en/.
I propose to create an additional ZIP named ISO-CD_PAS_8329_electronic-inserts.zip with all the files to be uploaded. I will then add a note to ISO CS, that they should upload these files to https://standards.iso.org/iso/pas/8329/ed-1/en/ .

**Comment by DrCaFr** [comment]
> What do you mean with "submit XML example files"? The snippets in the Word document or complete x.xml files to be uploaded to https://standards.iso.org/iso/pas/8329/ed-1/en/ ? 

Yes, actually those examples we collected in subdir [V3.1.1/examples](https://github.com/economidis-nick/createXSDforxMCF/tree/v3_1_1_editorial_changes/V3.1.1/examples).

> I propose to create an additional ZIP named ISO-CD_PAS_8329_electronic-inserts.zip with all the files to be uploaded. I will then add a note to ISO CS, that they should upload these files to https://standards.iso.org/iso/pas/8329/ed-1/en/ .

Naively, I would have added the schema file to the same ZIP as the Word (incl. PDF) & PowerPoint files. 
But a separate, distinct file for the "inserts" would surely be more appropriate! :wink:

**Comment by DrCaFr** [comment]
The question "How to submit XML example files" was decided. 
The new distribution script acts accordingly.

**Comment by DrCaFr** [comment]
@maxungerer uploaded recent distribution to ISO at 2023-04-20.
Hence, I close this issue,
