### ISSUE TITLE
Support _both_ widths of a Butt Joint

### ISSUE THREAD

**Issue by DrCaFr** [economidis-nick/createXSDforxMCF#97]
&chi;MCF version 3.1 contains the following section: 

![grafik](https://github.com/economidis-nick/createXSDforxMCF/assets/18173895/d65c693f-3070-4917-bb1b-aef972cf9be4)

Obviously, _only one_ of the _two_ widths _b<sub>1</sub>_ & _b<sub>2</sub>_ shown in Figure 49 are supported by the format, since Table 88 contains only one parameter _b_ "width". 

Following corrections are necessary:
1. Clarify whether parameter _b_ "width" refers to the primary or secondary side. 
2. Provide both parameters, _b<sub>1</sub>_ & _b<sub>2</sub>_ in Table 88.

Of course, according XML example files need to be updated then, too.

**Comment by DrCaFr** [comment]
Question in this context: How to specify in xMCF, what is _primary_ and what is _secondary_ side. 

Idea: _Primary_ side has the bigger width, i.e.  _b<sub>1</sub>_ &gt; _b<sub>2</sub>_. 
But what if both are equal?

**Comment by economidis-nick** [comment]
> Obviously, only one of the two widths b1 & b2 shown in Figure 49 are supported by the format, since Table 88 contains only one parameter b "width".

Note that the multiplicity of b ('width') in the table is also vague: 
 The primary width should have multiplicity of 1 and not 1-2  !!!
It is not clear in the table whether 'width' refers to b1 (primary side), or whether there are two 'widths'.

 We could change the table to the following:
![image](https://github.com/economidis-nick/createXSDforxMCF/assets/33229181/9856aaa5-8a8b-4d4f-ba50-8720466d77ca)

**Comment by DrCaFr** [comment]
After @economidis-nick's comment, I see similar issues with 

1. the **Corner Weld**:
![grafik](https://github.com/economidis-nick/createXSDforxMCF/assets/18173895/d54c67f2-13a2-4a72-b4b4-b4ad4ab76c20)  
Suggested solution:  
![grafik](https://github.com/economidis-nick/createXSDforxMCF/assets/18173895/da8381ed-43bb-488f-a2c6-2e1671cd4fbe)  
since we have each of these parameters max. once.

2. the **Double Corner Weld**:
![grafik](https://github.com/economidis-nick/createXSDforxMCF/assets/18173895/47847c10-cc97-4db4-a10a-0f95767834c3)

and

3. the **Y-Joint**: 
![grafik](https://github.com/economidis-nick/createXSDforxMCF/assets/18173895/f0180ccd-fedd-44ee-a23c-6c12d97ccba9)

**Comment by DrCaFr** [comment]
Yet another finding: The **Cruciform Joint**:
![grafik](https://github.com/economidis-nick/createXSDforxMCF/assets/18173895/68f0bee6-7b47-434d-b2e0-89e809a46259)

**Comment by economidis-nick** [comment]
> Obviously, only one of the two widths b1 & b2 shown in Figure 49 are supported by the format, since Table 88 contains only one parameter b "width".
>
> Following corrections are necessary:
> 
> Clarify whether parameter b "width" refers to the primary or secondary side.
> Provide both parameters, b1 & b2 in Table 88.

@DrCaFr , I read the text again. The tables are not wrong, striclty speaking. 
e.g. the buttweld can have more than 1 welding position in xmcf.
And each welding position expresses the (e, b, α, d, β)-values which are specified in the tables.

Perhaps they would be clearer if we mentioned that:
"Butt-Joint may have up to 2 welding positions. The features of _each_ welding position are 
* b    ( "width" in xmcf)
* e   ( not captured in xmcf)

Therefore, I would propose that we **remove the "Multiplicity" column from every table**, and state (before each table) that 
e.g. "the cruciform joint can have 2-4 welding positions, where each position has the following attributes"

**Comment by DrCaFr** [comment]
@economidis-nick: I had completely lost sight of the structure / schema of the XML file, here. Thank you for opening my eyes to this again! 
So it's not an error in the specification, but merely a sensible enhancement in the wording.  
I'm very relieved about that! 
Changed label from "Bug" to "enhancement", accordingly.

**Comment by economidis-nick** [comment]
### review

Inconsistency:
- On Table 93 (10.2.5.3) , reinforcement : xMCF-Key is '**(not yet supported)**'
- On Table 102 (10.2.7.3) , reinforcement : xMCF-Key is '**-**'   
I prefer the latter.

Inconsistency:
- On Table 102 (10.2.7.3) , title is 'Parameters of Edge weld for its **single** weld position'
- On Table 105 (10.2.8.3) , title is 'Parameters of I-Weld'         _(doesn't it have a **single** weld position?)_
- On Table 125 (10.2.13.2) , title is 'Parameters of Flared Joint for its **single** weld position'


Inconsistent Figures in 10.2.6.3.2:
- notice the difference between Figure 58 and 59 (at the bottom weldings)...

**Comment by DrCaFr** [comment]
Thanks again, @economidis-nick! 
I applied your suggestions with commit e8998813bd039d5c45701f1f6ebe32858cd705ba and close the issue, now.
